# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Default configuration for use with tic package
# tic documentation to get started: https://ropenscilabs.github.io/tic/
# Usually you shouldn't need to change the first part of the file

# DO NOT CHANGE THE CODE BELOW
before_install:
  - R -q -e 'if (!requireNamespace("remotes")) install.packages("remotes")'
  - R -q -e 'if (getRversion() < "3.2" && !requireNamespace("curl")) install.packages("curl")'
  - R -q -e 'remotes::install_github("ropenscilabs/tic", upgrade = "always"); print(tic::dsl_load()); tic::prepare_all_stages()'
  - R -q -e 'tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE

# Custom parts:

# Header
language: r
sudo: false
dist: xenial
cache:
- packages
- .Rcache
latex: false

#stages: test, full
stages:
- name: test
- name: full
  if:
  - branch = master OR branch = docs OR branch =~ /^r-.*$/

#jobs
jobs:
  include:
  - r: devel
  - r: release
    env:
    - TIC_ONLY_STYLER=true
  - r: 3.3
  - stage: full
    os: osx
  - r: release
    env:
    - TIC_BUILD_PKGDOWN=true
  - r: devel
    env:
    - TIC_DEV_VERSIONS=TRUE
    - TIC_ONLY_TESTS=TRUE
  - r: 3.5
  - r: 3.4
  allow_failures:
  - r: devel
    env:
    - TIC_DEV_VERSIONS=TRUE
    - TIC_ONLY_TESTS=TRUE
  - os: osx
  fast_finish: true

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - _R_CHECK_SYSTEM_CLOCK_=false
  - MAKEFLAGS="-j 2"
  - _R_CHECK_PACKAGE_DEPENDS_IGNORE_MISSING_ENHANCES_="true"

addons:
  apt:
    packages:
      - libv8-dev

#services
services:
