# This workflow calls the GitHub API very frequently.
# Can't be run as part of commits
on:
  schedule:
    - cron:  '0 1 * * *'
  push:
    branches:
      - main
      - master
    paths:
      - ".github/workflows/R-CMD-check-dev.yaml"

name: rcc dev

jobs:
  R-CMD-check:
    runs-on: ubuntu-18.04

    name: ${{ matrix.package }}

    # Begin custom: services
    # End custom: services

    strategy:
      fail-fast: false
      matrix:
        package:
          - sys
          - stringi
          - glue
          - askpass
          - stringr
          - R6
          - openssl
          - mime
          - jsonlite
          - curl
          - selectr
          - magrittr
          - httr
          - xml2
          - ps
          - markdown
          - highr
          - base64enc
          - digest
          - xfun
          - tinytex
          - evaluate
          - htmltools
          - yaml
          - knitr
          - processx
          - withr
          - whisker
          - rmarkdown
          - rlang
          - fs
          - clipr
          - callr
          - utf8
          - assertthat
          - vctrs
          - pkgconfig
          - pillar
          - lifecycle
          - fansi
          - ellipsis
          - cli
          - crayon
          - prettyunits
          - hms
          - rematch
          - progress
          - tibble
          - Rcpp
          - cellranger
          - cpp11
          - generics
          - dplyr
          - backports
          - tidyselect
          - tidyr
          - purrr
          - broom
          - BH
          - readr
          - forcats
          - rematch2
          - diffobj
          - rstudioapi
          - pkgbuild
          - rprojroot
          - waldo
          - praise
          - pkgload
          - desc
          - brio
          - colorspace
          - viridisLite
          - RColorBrewer
          - munsell
          - labeling
          - farver
          - testthat
          - scales
          - isoband
          - gtable
          - blob
          - DBI
          - bit
          - htmlwidgets
          - gridExtra
          - ggplot2
          - igraph
          - lazyeval
          - rvest
          - reprex
          - readxl
          - modelr
          - lubridate
          - haven
          - dbplyr
          - plogr
          - memoise
          - bit64
          - rappdirs
          - filelock
          - sodium
          - getPass
          - V8
          - visNetwork
          - viridis
          - influenceR
          - downloader
          - rex
          - tidyverse
          - RSQLite
          - RPostgres
          - RMariaDB
          - odbc
          - nycflights13
          - mockr
          - keyring
          - DiagrammeRsvg
          - DiagrammeR
          - covr
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # prevent rgl issues because no X11 display is available
      RGL_USE_NULL: true
      # Begin custom: env vars
      # End custom: env vars

    steps:
      - name: Check rate limits
        run: |
          curl -s --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit
        shell: bash

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install remotes
        run: |
          if (!requireNamespace("curl", quietly = TRUE)) install.packages("curl")
          if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes")
        shell: Rscript {0}

      - name: Prepare cache keys
        if: runner.os != 'Windows'
        id: date
        run: echo "::set-output name=date::$(date -Ihours)"

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ubuntu-18.04-r-dev-release-${{ matrix.package }}-${{steps.date.outputs.date}}
          restore-keys: ubuntu-18.04-r-dev-release-${{ matrix.package }}-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "18.04"))')

      # Begin custom: before install
      # End custom: before install

      - name: Install dependencies
        run: |
          deps <- remotes::dev_package_deps(dependencies = TRUE)
          update(deps)
          remotes::install_dev("${{ matrix.package }}")
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          if (!requireNamespace("sessioninfo", quietly = TRUE)) install.packages("sessioninfo")
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      # Begin custom: after install
      # End custom: after install

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_: false
          _R_CHECK_SYSTEM_CLOCK_: false
          _R_CHECK_FUTURE_FILE_TIMESTAMPS_: false
        run: |
          error_on <- "note"
          # Begin custom: rcmdcheck error_on
          # End custom: rcmdcheck error_on
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = error_on, check_dir = "check")
        shell: Rscript {0}

      - name: Show test output
        if: always()
        run: find check -name '*.Rout*' -exec head -n 1000000 '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.package }}-results
          path: check

      - name: Check rate limits
        if: always()
        run: |
          curl -s --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit
        shell: bash
