## tic GitHub Actions template: custom-deploy
## revision date: 2020-05-21
on:
  push:
  pull_request:
  # for now, CRON jobs only run on the default branch of the repo (i.e. usually on master)
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 4 * * *"

name: tic

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    # [Custom matrix name]
    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) (${{ matrix.config.id }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # Custom configs
          # [Custom matrix env var]
          - { os: ubuntu-latest, r: 3.6, id: "default" }
          # [Custom matrix env var]
          - { os: ubuntu-latest, r: 3.3, id: "default" }
          # [Custom matrix env var]
          - { os: ubuntu-latest, r: "release", TIC_ONLY_IMPORTS: true, id: "TIC_ONLY_IMPORTS" }

    env:
      # [Custom env var]
      _R_CHECK_FORCE_SUGGESTS_: false
      # [Custom env var]
      _R_CHECK_SYSTEM_CLOCK_: false
      # [Custom env var]
      _R_CHECK_PACKAGE_DEPENDS_IGNORE_MISSING_ENHANCES: true
      # [Custom env var]
      TIC_DEV_VERSIONS: ${{ matrix.config.TIC_DEV_VERSIONS }}
      # [Custom env var]
      TIC_ONLY_IMPORTS: ${{ matrix.config.TIC_ONLY_IMPORTS }}
      # [Custom env var]
      TIC_ONLY_TESTS: ${{ matrix.config.TIC_ONLY_TESTS }}
      # [Custom env var]
      TIC_ONLY_STYLER: ${{ matrix.config.TIC_ONLY_STYLER }}
      # [Custom env var]
      MODE: ${{ matrix.config.MODE }}
      # otherwise remotes::fun() errors cause the build to fail. Example: Unavailability of binaries
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}
      # make sure to run `tic::use_ghactions_deploy()` to set up deployment
      TIC_DEPLOY_KEY: ${{ secrets.TIC_DEPLOY_KEY }}
      # prevent rgl issues because no X11 display is available
      RGL_USE_NULL: true
      # if you use bookdown or blogdown, replace "PKGDOWN" by the respective
      # capitalized term. This also might need to be done in tic.R
      TIC_BUILD_PKGDOWN: ${{ matrix.config.pkgdown }}
      # macOS >= 10.15.4 linking
      SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
      # [Custom env var] use GITHUB_TOKEN from GitHub to workaround rate limits in {remotes}
      GITHUB_PAT: ${{ secrets.DM_PAT }}

    steps:
      - uses: actions/checkout@v2.1.1

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          Ncpus: 4

      # LaTeX. Installation time:
      # Linux: ~ 1 min
      # macOS: ~ 1 min 30s
      # Windows: never finishes
      - uses: r-lib/actions/setup-tinytex@v1
        if: runner.id == 'pkgdown'

      - uses: r-lib/actions/setup-pandoc@master

      # set date/week for use in cache creation
      # https://github.community/t5/GitHub-Actions/How-to-set-and-access-a-Workflow-variable/m-p/42970
      # - cache R packages daily
      # - cache ccache weekly -> 'ccache' helps rebuilding the package cache faster
      - name: "[Cache] Prepare daily timestamp for cache"
        if: runner.os != 'Windows'
        id: date
        run: echo "::set-output name=date::$(date '+%d-%m')"

      - name: "[Cache] Cache R packages"
        if: runner.os != 'Windows'
        uses: pat-s/always-upload-cache@v2.0.0
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ steps.date.outputs.date }}-${{ matrix.config.cache }}-${{ matrix.config.id }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ steps.date.outputs.date }}-${{ matrix.config.cache }}-${{ matrix.config.id }}

      # install ccache and write config file
      - name: "[Linux] Prepare"
        if: runner.os == 'Linux'
        run: |
          sudo apt install libcurl4-openssl-dev

      - name: "[Custom block] [Linux] Install libraries"
        if: runner.os == 'Linux'
        run: |
          sudo apt install libpq-dev libmysqlclient-dev libssh2-1-dev libsodium-dev libv8-dev

      # for some strange Windows reason this step and the next one need to be decoupled
      - name: "[Stage] Prepare"
        run: |
          Rscript -e "if (!requireNamespace('remotes')) install.packages('remotes', type = 'source')"
          Rscript -e "if (getRversion() < '3.2' && !requireNamespace('curl')) install.packages('curl', type = 'source')"

      - name: "[Custom block] [macOS] Install v8"
        if: runner.os == 'macOS'
        run: |
          # for DiagrammeRsvg
          brew install v8

      - name: "[Stage] Install"
        if: matrix.config.os != 'macOS-latest' || matrix.config.r != 'devel'
        run: Rscript -e "remotes::install_github('ropensci/tic')" -e "print(tic::dsl_load())" -e "tic::prepare_all_stages()" -e "tic::before_install()" -e "tic::install()"

      # macOS devel needs its own stage because we need to work with an option to suppress the usage of binaries
      - name: "[Stage] Prepare & Install (macOS-devel)"
        if: matrix.config.os == 'macOS-latest' && matrix.config.r == 'devel'
        run: |
          echo -e 'options(Ncpus = 4, pkgType = "source", repos = structure(c(CRAN = "https://cloud.r-project.org/")))' > $HOME/.Rprofile
          Rscript -e "remotes::install_github('ropensci/tic')" -e "print(tic::dsl_load())" -e "tic::prepare_all_stages()" -e "tic::before_install()" -e "tic::install()"

      - name: "[Stage] Script"
        run: Rscript -e 'tic::script()'

      - name: "[Stage] After Success"
        if: matrix.config.os == 'macOS-latest' && matrix.config.r == 'release'
        run: Rscript -e "tic::after_success()"

      - name: "[Stage] Upload R CMD check artifacts"
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
      - name: "[Stage] Before Deploy"
        run: |
          Rscript -e "tic::before_deploy()"

      - name: "[Stage] Deploy"
        run: Rscript -e "tic::deploy()"

      - name: "[Stage] After Deploy"
        run: Rscript -e "tic::after_deploy()"
